add option to remove top panel
edfloreshz/cosmic-tweaks pull request #1
Opened 2024-05-03 11:50 UTC by leb-kuchen

2024-05-03 17:24 UTC, edfloreshz commented
Isn't this the same as disabling the top panel in COSMIC Settings?

2024-05-03 19:00 UTC, git-f0x commented
I believe only the Dock can be disabled. There isn't a toggle for that in Panel settings.

2024-05-03 19:02 UTC, edfloreshz commented
True! I'll review this a bit later then.

2024-05-04 09:27 UTC, edfloreshz commented on src/pages/panel.rs
> +                    widget::settings::item::builder("Show panel")
Could you add a key for this in `i18n/en/cosmic_tweaks.ftl`?

2024-05-04 09:28 UTC, edfloreshz requested changes
Please resolve the comment and we can merge 👍🏼

2024-05-04 17:33 UTC, edfloreshz approved these changes
LGTM

2024-05-04 17:33 UTC, merged

2024-05-04 17:33 UTC, edfloreshz commented
Thanks! 🎉